export const header: string;
export const content: string;
export const active: string;
export const leftContainer: string;
export const rightContainer: string;
export const asideContainer: string;
export const btn: string;
export const register: string;
export const avatarContainer: string;
